stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - echo "Building mobile m app"

test:
  stage: test
  script:
    - echo "Testing mobile ,app"

deploy:
  stage: deploy
  script:
    - echo "Deploying mobile app"
