version: '3.8'

services:
    
  nginx:
    depends_on:
      - api
      - zinkinew
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
         
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "4004:5000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
